### ISSUE TITLE
Age-group incidence rates

### ISSUE THREAD

**Issue by rgieseke** [dbvis-ukon/coronavis#1]
Hi there!

I think your incidence rates for the age groups are too high, since you use 2011 census data.
I've added downloads from RKI-calculated incidence rates to my scripts, see here for the call to use the correct years.

https://github.com/rgieseke/opencoviddata/blob/main/scripts/fetch-county-incidence.py#L60

**Comment by wjentner** [comment]
Wow ok that filter setting was not clear to me. I will fix it ASAP in our code. Thank you so much for the hint!

**Comment by wjentner** [comment]
Fixed by https://github.com/dbvis-ukon/coronavis/releases/tag/v1.19.15

**Comment by rgieseke** [comment]
:+1: 
Maybe you could style the last, on-going week differently to make it clearer that it's still being updated (might not be obvious to every visitor even though it is stated at the bottom).

Do you now use the direct incidence data from SurvStat? I'm not sure which population dataset they use.
For the state data i checked that incidence rates are the same when using the 2019 data included in my repo. (For the counties i'm not sure, and i think they might interpolate somehow or they have access to more fine-grained data than those available from statistical offices.)

**Comment by wjentner** [comment]
I've asked them what they are using, and they said it's the 2019 dataset. No idea whether they interpolate the numbers per county or have special access to some data which is not "publicly available".
Anyhow, since they allow to download both numbers, the absolute case numbers and the incidence rates, I simply wrote a tiny little script to calculate the population based on this: https://github.com/dbvis-ukon/coronavis/blob/master/misc/notebooks/survestat.ipynb (ln [6]).
We store the population numbers permanently, update only the absolute case numbers hourly, and calculate the rest in the frontend.
By doing that, we can very flexibly calculate any age groups and render the chart: https://github.com/dbvis-ukon/coronavis/blob/master/Frontend/gis/src/app/services/vega-pixelchart.service.ts#L63
